project_id = "glrgfnqdzwbpkcsoxsgd"

[functions.get-agent-context]
verify_jwt = false

[functions.agent-chat]
verify_jwt = false

[functions.generate-post-image]
verify_jwt = false

[functions.save-analytics]
verify_jwt = false

[functions.get-analytics]
verify_jwt = false

[functions.save-scanned-posts]
verify_jwt = false

[functions.get-writing-style]
verify_jwt = false

[functions.sync-post]
verify_jwt = false

[functions.sync-analytics]
verify_jwt = false

[functions.sync-profile]
verify_jwt = false

[functions.process-scheduled-posts]
verify_jwt = false

[functions.post-success]
verify_jwt = false

[functions.check-overdue-posts]
verify_jwt = false

[functions.razorpay-payment]
verify_jwt = false
